[palette]
# COPIED from helix's catppuccin_mocha theme

# catppuccin palette colors
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# derived colors by blending existing palette colors
cursorline = "#2a2b3c"
secondary_cursor = "#b5a6a8"
secondary_cursor_normal = "#878ec0"
secondary_cursor_insert = "#7da87e"

# muted versions of main colors, by srs
red1 = "#a65e73"

[defaultAttr]
bg = "base"
fg = "text"

[theme]

# Helix uses mantle instead of crust but I think it's also got better color accuracy.
"tab_bar" = {fg = "subtext1", bg = "crust"}
# "tab_bar.tab_title" = {}  # Unused
"tab_bar.selected.tab_title" = {fg = "mauve", bg = "base", style = "underline"}

"section_header" = {style = "underline"}

# SOMEDAY some background would be nice
"filter_label" = {fg = "blue"}

# SOMEDAY maybe a bit too subtle.
"selected" = {bg = "surface1"}

"status.next" = {fg = "green"}
"status.waiting" = {fg = "pink"}
"status.project" = {fg = "green"}
"status.later" = {fg = "teal"}
"status.wip" = {fg = "yellow"}
"status.done" = {fg = "overlay1"}
"status.someday" = {fg = "mauve"}
# SOMEDAY quite sure yet what's most readable.
# "status.open" = {fg = "maroon"}
# "status.open" = {fg = "peach"}
"status.open" = {fg = "sapphire"}
# "status.open" = {fg = "lavender"}

# SOMEDAY a bit annoying that we don't have the right kind of inheritance, so we have to duplicate this.
# (it's the same as without selected)
"selected.status.next" = {fg = "green"}
"selected.status.waiting" = {fg = "pink"}
"selected.status.project" = {fg = "green"}
"selected.status.later" = {fg = "teal"}
"selected.status.wip" = {fg = "yellow"}
"selected.status.done" = {fg = "overlay1"}
"selected.status.someday" = {fg = "mauve"}
"selected.status.open" = {fg = "sapphire"}

# TODO 'bold' doesn't really work. (but italic and underline do)
# Seems to be a kitty issue. I once saw a TUI demo where it *did* work, though!
"date.deadline" = {style = "underline"}
"date.deadline.today" = {fg = "yellow", style = "underline"}
"date.deadline.tomorrow" = {fg = "green", style = "underline"}
"date.deadline.overdue" = {fg = "red", style = "underline"}

"date.goalline.today" = {fg = "yellow"}
"date.goalline.tomorrow" = {fg = "green"}
"date.goalline.overdue" = {fg = "red"}

"date.scheduled.today" = {fg = "yellow"}
"date.scheduled.overdue" = {fg = "red"}

"date.remind.today" = {fg = "green"}
"date.remind.overdue" = {fg = "yellow"}

# TODO another instance of the current attr mechanism being incredibly inconvenient
"date.indirect" = {fg = "overlay1", style = "italic"}

"date.indirect.deadline.overdue" = {fg = "red1", style = "italic,underline"}

# "date.deadline" = {style = "underline"}
# "date.deadline.today" = {fg = "yellow", style = "underline"}
# "date.deadline.tomorrow" = {fg = "green", style = "underline"}
# "date.deadline.overdue" = {fg = "red", style = "underline"}

# "date.goalline.today" = {fg = "yellow"}
# "date.goalline.tomorrow" = {fg = "green"}
# "date.goalline.overdue" = {fg = "red"}

# "date.scheduled.today" = {fg = "yellow"}
# "date.scheduled.overdue" = {fg = "red"}

# "date.remind.today" = {fg = "green"}
# "date.remind.overdue" = {fg = "yellow"}

