[palette]
# COPIED from helix's catppuccin_mocha theme

# catppuccin palette colors
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"

base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# derived colors by blending existing palette colors
cursorline = "#2a2b3c"
secondary_cursor = "#b5a6a8"
secondary_cursor_normal = "#878ec0"
secondary_cursor_insert = "#7da87e"

[defaultAttr]
bg = "base"
fg = "text"

[theme]

# SOMEDAY some background would be nice
"filter_label" = {fg = "blue"}

# SOMEDAY maybe a bit too subtle.
"selected" = {bg = "surface1"}

"status.next" = {fg = "green"}
"status.waiting" = {fg = "red"}
"status.project" = {fg = "blue"}
"status.later" = {fg = "teal"}
"status.wip" = {fg = "peach"}
"status.done" = {fg = "overlay1"}
"status.someday" = {fg = "mauve"}

# SOMEDAY a bit annoying that we don't have the right kind of inheritance, so we have to duplicate this.
# (it's the same as without selected)
"selected.status.next" = {fg = "green"}
"selected.status.waiting" = {fg = "red"}
"selected.status.project" = {fg = "blue"}
"selected.status.later" = {fg = "teal"}
"selected.status.wip" = {fg = "peach"}
"selected.status.done" = {fg = "overlay1"}
"selected.status.someday" = {fg = "mauve"}

